ÂåÖÂêç:cadabra2.linyaps
LayerÊñá‰ª∂:cadabra2.linyaps_2.4.5.0_x86_64_binary.layer
BaseÊñá‰ª∂Á≥ªÁªü:/home/runner/.cache/linglong-builder/repo/../layers/main/org.deepin.base/23.1.0/x86_64/binary/files
RuntimeÊñá‰ª∂Á≥ªÁªü:
disk: cadabra2.linyaps_2.4.5.0_x86_64_binary.layer
offset: 815
mountpoint: /tmp/tmp.jrs1tKejqa/mnt
dbglevel: 0
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

(cadabra2-gtk:36): dbind-[1;33mWARNING[0m **: [34m13:07:26.083[0m: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
terminate called after throwing an instance of 'std::runtime_error'
  what():  FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.12/dist-packages/cadabra2_defaults.py'

At:
  Notebook Cell (Line 1): f=open(r'/usr/local/lib/python3.12/dist-packages/cadabra2_defaults.py'); code=compile(f.read(), 'cadabra2_defaults.py', 'exec'); exec(code); f.close()

terminate called after throwing an instance of 'std::logic_error'
  what():  Failed to read port from server.
